# Generated by Django 5.0.1 on 2024-05-05 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_estate_alter_month_rate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to=settings.AUTH_USER_MODEL),
        ),
    ]
